# GitLab SAST (Static Application Security Testing) via CI/CD
# SAST scanning can be DISABLED by commenting it out.
include:
  - template: Jobs/SAST.gitlab-ci.yml

variables:
  SCAN_KUBERNETES_MANIFESTS: 'true'

# List of stages for jobs, and their order of execution
# Note: The "- test" stage is needed for GitLab's SAST. Which, we don't need it fully defined below.
stages:
  - build
  - test
  #- deploy

build-job:
  # Uses the older `erbium` Node.js on purpose.
  # Yarn v1 is already included in the image, which we need as Yarn both builds and does unit testing.
  stage: build
  image: node:erbium
  script:
    - 'echo "Current directory: $(pwd)"'
    - 'echo "NPM version: $(npm --version)"'
    #- 'npm install --global yarn'
    - 'echo "Yarn version: $(yarn --version)"'
    - 'echo "Hello world"'
#
# To login to Docker Hub:
#sudo echo -n $(aws secretsmanager get-secret-value --secret-id docker-hub-token-for-gitlab-cicd --profile gitlab-cicd --query SecretString --output text | cut -d: -f2 | tr -d \"}) | sudo docker login -u junktext --password-stdin

