# List of stages for jobs, and their order of execution
stages:
  - build   # Yarn install, Prettier formatting checks, & Jest unit tests
  - test    # GitLab's SAST
  - deploy  # Containerize, deploy to Docker Hub, & update the Helm Chart (which can activate GitOps K8s rollout)

# Job: Build when a Git tag is NOT present.
build-on-commit:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH
      when: always
  trigger:
    include:
      - local: '.gitlab-ci-1-build.yml'

# Job: Test when Git tag is NOT present.
test-on-commit:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH
      when: always
  trigger:
    include:
      - local: '.gitlab-ci-2-test.yml'

# Job: Deploy when a Git tag is ACTUALLY present.
deploy-with-git-tag:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: always
  trigger:
    include:
      - local: '.gitlab-ci-3-deploy.yml'
