include:
  # Build and test when no Git tag is present.
  - local: '.gitlab-ci-build-and-test.yml'
    rules:
      - if: $CI_COMMIT_TAG
        when: never
  # Deploy when a Git tag is present.
  - local: '.gitlab-cit-deploy.yml'
    rules:
      - if: $CI_COMMIT_TAG
        when: always
