services:
  web:
    image: junktext/getting-started:latest
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_DB: todos

  database:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
