FROM node:12-alpine
# Adding build tools to make yarn install work on Apple silicon / arm64 machines
RUN apk add --no-cache python2 g++ make
WORKDIR /app
# Image layer caching via dependency caching.
COPY package.json yarn.lock ./
# Yarn Classic: We're not specifying --production, so it is for dev.
RUN yarn install
COPY . .
CMD ["yarn", "run", "dev"]