apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}  # Chart.yaml: The 'name' scalar.
  name: {{ .Release.Name }} # Name of the local Helm release.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app-ver: {{ .Chart.AppVersion }}
        helm-chart-ver: {{ .Chart.Version }}
    spec:
      containers:
        # Parses into something like: junktext/getting-started:1.0.4
      - image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}
        # We only have 1 container in each Pod, so we can just a simple name.
        name: {{ .Release.Name }}
        ports:
          - containerPort: {{ .Values.service.port }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits: 
            memory: "128Mi"
            cpu: "200m"
